language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio update
- platformio lib -g install 1

env:
- BOARD=esp12e

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - pio lib install https://github.com/jaycollett/MQTTUSBSwitch.git
  - pio lib install "PubSubClient"
  - pio lib install "DNSServer"
  - pio lib install "WiFiManager"
  - platformio ci --board=$BOARD --lib=$PWD/Arduino\ Code/MQTTUSBSwitchFirmware $PWD/Arduino\ Code/MQTTUSBSwitchFirmware/MQTTUSBSwitchFirmware.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
